version: '3.3'
services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - ./AxonServer/data:/data
      - ./AxonServer/eventdata:/eventdata
      - ./AxonServer/config:/config:ro
    ports:
      - '8025:8025'
      - '8124:8124'
      - '8224:8224'
    networks:
      - events-stack-network

  apigateway:
    build: ApiGateway
    depends_on:
      - discoveryserver
    ports:
      - '8082:8082'
    networks:
      - events-stack-network
  discoveryserver:
    build: DiscoveryServer
    depends_on:
      - axonserver
    ports:
      - '8761:8761'
    networks:
      - events-stack-network
  productservice:
    build: ProductService
    depends_on:
      - axonserver
      - discoveryserver
      - apigateway
    ports:
      - '8080:8080'
    volumes:
      - ./h2db:/tmp/events-ms-stack/h2db
    environment:
      spring.datasource.url: "jdbc:h2:file:/tmp/events-ms-stack/h2db/products.db;AUTO_SERVER=true"
    networks:
      - events-stack-network
  orderservice:
    build: OrderService
    depends_on:
      - axonserver
      - discoveryserver
      - apigateway
    ports:
      - '8089:8089'
    volumes:
      - ./h2db:/tmp/events-ms-stack/h2db
    environment:
      spring.datasource.url: "jdbc:h2:file:/tmp/events-ms-stack/h2db/orders.db;AUTO_SERVER=true"
    networks:
      - events-stack-network
networks:
  events-stack-network: