version: '3.3'
services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - ./data:/data
      - ./eventdata:/eventdata
      - ./config:/config:ro
    ports:
      - '8025:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-demo
networks:
  axon-demo: